from os import path, curdir

LANDSCAPES_COUNT = 10
LANDSCAPE_COST_MAX = 10
LANDSCAPE_COST_MIN = 1

ALPHA_MAX = 1.0
ALPHA_MIN = 0.0

BETA_MAX = 1.0
BETA_MIN = 0.0

MAP_SIZE = 10

INPUT_DIR = path.join(path.abspath(curdir), "data")

WILL_BACKUP = False

LANDSCAPES_FILENAME = "landscapes.json"
MAP_FILENAME = "map.json"
PARAMS_FILENAME = "params.json"

LANDSCAPES_PATH = path.join(INPUT_DIR, LANDSCAPES_FILENAME)
MAP_PATH = path.join(INPUT_DIR, MAP_FILENAME)
PARAMS_PATH = path.join(INPUT_DIR, PARAMS_FILENAME)

SIZE = 1

# PSO hyperparameters
STEPS_COUNT = 1000
SWARM_SIZE = 200
CURRENT_VELOCITY_RATIO = 0.1
LOCAL_VELOCITY_RATIO = 1.0
GLOBAL_VELOCITY_RATIO = 5.0
